channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=25.1
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - packaging==24.2
  - pandas==2.2.3
  - psutil==5.9.0
  - pyyaml==6.0.2
  - scikit-learn==1.6.1
  - scipy==1.15.3
  - matplotlib==3.10.3
  - seaborn==0.13.2
name: mlflow-env